language: cpp

sudo: required
dist: trusty

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - os: osx
          compiler: clang

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y &&
      sudo apt-get update -qq
    fi
  - eval "${MATRIX_EVAL}"

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get -y install qt59base libfuse-dev libmagic-dev &&
      source /opt/qt*/bin/qt*-env.sh
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install qt5
    fi

script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr &&
      make -j$(nproc) &&
      make DESTDIR=appdir -j$(nproc) install ; find appdir/ &&
      sed -i -e 's|^Name=.*|Name=Android File Transfer|g' appdir/usr/share/applications/android-file-transfer.desktop &&
      wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" &&
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage &&
      unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH &&
      export VERSION=$(git rev-parse --short HEAD) &&
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs &&
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      mkdir build &&
      cd build &&
      cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=$(pwd)/installdir &&
      make -j$(sysctl -n hw.ncpu) &&
      make install &&
      mv installdir/android-file-transfer.app installdir/Android\ File\ Transfer\ for\ Linux.app &&
      git clone https://github.com/andreyvit/create-dmg.git &&
      cd create-dmg &&
      ./create-dmg --volicon "../../osx/android-file-transfer.icns" --icon-size 96 --icon "Android File Transfer for Linux" 110 100 --app-drop-link 380 100 AndroidFileTransferForLinux.dmg ../installdir/Android\ File\ Transfer\ for\ Linux.app
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq &&
      bash upload.sh ./Android*.AppImage*
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      bash upload.sh AndroidFileTransferForLinux.dmg
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
